# Generated by Django 4.1.6 on 2023-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_gw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='ip адрес')),
                ('mac', models.CharField(max_length=13, unique=True, verbose_name='MAC адрес')),
                ('login1', models.CharField(max_length=20, verbose_name='Логин 1 порта')),
                ('password1', models.CharField(max_length=20, verbose_name='Пароль 1 порта')),
                ('login2', models.CharField(max_length=20, verbose_name='Логин 2 порта')),
                ('password2', models.CharField(max_length=20, verbose_name='Пароль 2 порта')),
            ],
        ),
    ]
