# Generated by Django 4.1.6 on 2023-03-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiocodesMP112',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='ip адрес')),
                ('mac', models.CharField(max_length=13, unique=True, verbose_name='MAC адрес')),
                ('login1', models.CharField(max_length=20, verbose_name='Логин 1 порта')),
                ('password1', models.CharField(max_length=20, verbose_name='Пароль 1 порта')),
                ('login2', models.CharField(max_length=20, verbose_name='Логин 2 порта')),
                ('password2', models.CharField(max_length=20, verbose_name='Пароль 2 порта')),
            ],
            options={
                'verbose_name': 'ГШ тест',
                'verbose_name_plural': 'ГШ тестs',
            },
        ),
        migrations.CreateModel(
            name='TypeAudiocodesMP112',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.DeleteModel(
            name='Test_gw',
        ),
        migrations.AddField(
            model_name='audiocodesmp112',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicegateway.typeaudiocodesmp112'),
        ),
    ]
