# Generated by Django 4.1.6 on 2023-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0004_alter_audiocodesmp112_login1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocodesmp112',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Описание ГШ'),
        ),
    ]
