# Generated by Django 4.1.6 on 2023-03-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0005_audiocodesmp112_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocodesmp112',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание ГШ'),
        ),
        migrations.AlterField(
            model_name='audiocodesmp112',
            name='login1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Логин 1 порта'),
        ),
        migrations.AlterField(
            model_name='audiocodesmp112',
            name='login2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Логин 2 порта'),
        ),
        migrations.AlterField(
            model_name='audiocodesmp112',
            name='password1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль 1 порта'),
        ),
        migrations.AlterField(
            model_name='audiocodesmp112',
            name='password2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль 2 порта'),
        ),
    ]
