# Generated by Django 4.1.6 on 2023-03-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0006_alter_audiocodesmp112_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50, unique=True)),
                ('softswitch', models.CharField(max_length=50, verbose_name='Платформа')),
                ('ports', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Таблица типов голосовых шлюзов',
                'verbose_name_plural': 'Таблицы типов голосовых шлюзов',
            },
        ),
        migrations.CreateModel(
            name='MainGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gw', models.CharField(max_length=30, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='ip адрес')),
                ('mac', models.CharField(max_length=13, unique=True, verbose_name='MAC адрес')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicegateway.typegateway')),
            ],
            options={
                'verbose_name': 'Основная таблица голосовых шлюзов',
                'verbose_name_plural': 'Основные таблицы голосовых шлюзов',
            },
        ),
        migrations.CreateModel(
            name='LoginPasswordGW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=20, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль')),
                ('number_ports', models.IntegerField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicegateway.maingateway')),
            ],
            options={
                'verbose_name': 'Таблица логинов и паролей',
                'verbose_name_plural': 'Таблицы логинов и паролей',
            },
        ),
    ]
