# Generated by Django 4.1.6 on 2023-03-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0007_typegateway_maingateway_loginpasswordgw'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loginpasswordgw',
            unique_together={('gateway', 'number_ports')},
        ),
    ]
