# Generated by Django 4.1.6 on 2023-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0009_alter_maingateway_options_alter_typegateway_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typegateway',
            name='template_uri',
            field=models.CharField(default='', max_length=50),
        ),
    ]
