# Generated by Django 4.1.6 on 2023-03-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicegateway', '0010_typegateway_template_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typegateway',
            name='template_uri',
        ),
    ]
